project_id = "qwddqoyewtozzdvfmavn"

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.validate-display-token]
verify_jwt = false

[functions.get-wallboard-data]
verify_jwt = false

[functions.transcribe-call]
verify_jwt = true
