import React, { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Play, Pause, RotateCcw, Volume2, Loader2, CheckCircle, Sparkles } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

interface QACoachingAudioPlayerProps {
  bookingId: string;
  audioUrl?: string | null;
  listenedAt?: string | null;
  onAudioListened?: () => void;
  canRegenerate?: boolean;
  qaScore?: number;
  weakestAreas?: string[];
  compact?: boolean;
}

export const QACoachingAudioPlayer: React.FC<QACoachingAudioPlayerProps> = ({
  bookingId,
  audioUrl,
  listenedAt,
  onAudioListened,
  canRegenerate = false,
  qaScore,
  weakestAreas = [],
  compact = false,
}) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [duration, setDuration] = useState(0);
  const [currentAudioUrl, setCurrentAudioUrl] = useState(audioUrl);
  const [hasListened, setHasListened] = useState(!!listenedAt);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  useEffect(() => {
    setCurrentAudioUrl(audioUrl);
    setHasListened(!!listenedAt);
  }, [audioUrl, listenedAt]);

  const handlePlayPause = async () => {
    if (!audioRef.current || !currentAudioUrl) return;

    if (isPlaying) {
      audioRef.current.pause();
      setIsPlaying(false);
    } else {
      try {
        await audioRef.current.play();
        setIsPlaying(true);

        // Mark as listened on first play
        if (!hasListened) {
          await markAsListened();
        }
      } catch (error) {
        console.error('Error playing audio:', error);
        toast.error('Failed to play audio');
      }
    }
  };

  const markAsListened = async () => {
    try {
      const { error } = await supabase
        .from('booking_transcriptions')
        .update({ qa_coaching_audio_listened_at: new Date().toISOString() })
        .eq('booking_id', bookingId);

      if (!error) {
        setHasListened(true);
        onAudioListened?.();
      }
    } catch (error) {
      console.error('Error marking as listened:', error);
    }
  };

  const handleTimeUpdate = () => {
    if (audioRef.current) {
      const currentProgress = (audioRef.current.currentTime / audioRef.current.duration) * 100;
      setProgress(currentProgress);
    }
  };

  const handleLoadedMetadata = () => {
    if (audioRef.current) {
      setDuration(audioRef.current.duration);
    }
  };

  const handleEnded = () => {
    setIsPlaying(false);
    setProgress(0);
  };

  const handleGenerateAudio = async () => {
    setIsGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke('generate-qa-coaching-audio', {
        body: { bookingId, isRegenerate: !!currentAudioUrl }
      });

      if (error) throw error;

      if (data?.audioUrl) {
        setCurrentAudioUrl(data.audioUrl);
        toast.success('QA coaching audio generated by Katty!');
      }
    } catch (error) {
      console.error('Error generating QA coaching audio:', error);
      toast.error('Failed to generate QA coaching audio');
    } finally {
      setIsGenerating(false);
    }
  };

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  if (compact) {
    return (
      <div className="flex items-center gap-2">
        {currentAudioUrl ? (
          <>
            <audio
              ref={audioRef}
              src={currentAudioUrl}
              onTimeUpdate={handleTimeUpdate}
              onLoadedMetadata={handleLoadedMetadata}
              onEnded={handleEnded}
            />
            <Button
              variant="ghost"
              size="sm"
              className="h-8 w-8 p-0"
              onClick={handlePlayPause}
            >
              {isPlaying ? (
                <Pause className="h-4 w-4" />
              ) : (
                <Play className="h-4 w-4" />
              )}
            </Button>
            {hasListened && (
              <Badge variant="outline" className="bg-green-500/10 text-green-600 border-green-500/20 text-xs">
                <CheckCircle className="h-3 w-3 mr-1" />
                Listened
              </Badge>
            )}
          </>
        ) : canRegenerate ? (
          <Button
            variant="ghost"
            size="sm"
            onClick={handleGenerateAudio}
            disabled={isGenerating}
            className="text-xs"
          >
            {isGenerating ? (
              <Loader2 className="h-3 w-3 animate-spin mr-1" />
            ) : (
              <Sparkles className="h-3 w-3 mr-1" />
            )}
            Generate
          </Button>
        ) : (
          <span className="text-xs text-muted-foreground">No audio</span>
        )}
      </div>
    );
  }

  return (
    <div className="rounded-lg border bg-card p-4">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <div className="h-8 w-8 rounded-full bg-pink-500/20 flex items-center justify-center">
            <Volume2 className="h-4 w-4 text-pink-500" />
          </div>
          <div>
            <span className="text-sm font-medium">Katty's QA Coaching</span>
            {qaScore !== undefined && (
              <span className="text-xs text-muted-foreground ml-2">
                Score: {qaScore}%
              </span>
            )}
          </div>
        </div>
        {hasListened && (
          <Badge variant="outline" className="bg-green-500/10 text-green-600 border-green-500/20">
            <CheckCircle className="h-3 w-3 mr-1" />
            Listened
          </Badge>
        )}
      </div>

      {weakestAreas.length > 0 && (
        <div className="mb-3">
          <span className="text-xs text-muted-foreground">Focus Areas:</span>
          <div className="flex flex-wrap gap-1 mt-1">
            {weakestAreas.map((area, index) => (
              <Badge key={index} variant="secondary" className="text-xs">
                {area}
              </Badge>
            ))}
          </div>
        </div>
      )}

      {currentAudioUrl ? (
        <>
          <audio
            ref={audioRef}
            src={currentAudioUrl}
            onTimeUpdate={handleTimeUpdate}
            onLoadedMetadata={handleLoadedMetadata}
            onEnded={handleEnded}
          />

          <div className="space-y-2">
            <div className="h-2 bg-secondary rounded-full overflow-hidden">
              <div
                className="h-full bg-pink-500 transition-all duration-100"
                style={{ width: `${progress}%` }}
              />
            </div>

            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  className="h-9 w-9 p-0 rounded-full"
                  onClick={handlePlayPause}
                >
                  {isPlaying ? (
                    <Pause className="h-4 w-4" />
                  ) : (
                    <Play className="h-4 w-4 ml-0.5" />
                  )}
                </Button>
                <span className="text-xs text-muted-foreground">
                  {formatTime(audioRef.current?.currentTime || 0)} / {formatTime(duration)}
                </span>
              </div>

              {canRegenerate && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleGenerateAudio}
                  disabled={isGenerating}
                  className="text-xs"
                >
                  {isGenerating ? (
                    <Loader2 className="h-3 w-3 animate-spin mr-1" />
                  ) : (
                    <RotateCcw className="h-3 w-3 mr-1" />
                  )}
                  Regenerate
                </Button>
              )}
            </div>
          </div>
        </>
      ) : (
        <div className="flex items-center justify-center py-4">
          <Button
            variant="outline"
            onClick={handleGenerateAudio}
            disabled={isGenerating}
            className="gap-2"
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Katty is preparing your coaching...
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" />
                Generate QA Coaching from Katty
              </>
            )}
          </Button>
        </div>
      )}
    </div>
  );
};
