import React, { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Play, Pause, Volume2, Loader2, CheckCircle, Sparkles } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';
import { useAuth } from '@/contexts/AuthContext';

interface QACoachingAudioPlayerProps {
  bookingId: string;
  audioUrl?: string | null;
  listenedAt?: string | null;
  onAudioListened?: () => void;
  qaScore?: number;
  weakestAreas?: string[];
  variant?: 'button' | 'card';
  agentUserId?: string; // The user_id of the agent this coaching belongs to
}

export const QACoachingAudioPlayer: React.FC<QACoachingAudioPlayerProps> = ({
  bookingId,
  audioUrl,
  listenedAt,
  onAudioListened,
  qaScore,
  weakestAreas = [],
  variant = 'card',
  agentUserId,
}) => {
  const { user } = useAuth();
  const [isPlaying, setIsPlaying] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [duration, setDuration] = useState(0);
  const [currentAudioUrl, setCurrentAudioUrl] = useState(audioUrl);
  const [hasListened, setHasListened] = useState(!!listenedAt);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  useEffect(() => {
    setCurrentAudioUrl(audioUrl);
    setHasListened(!!listenedAt);
  }, [audioUrl, listenedAt]);

  const handlePlayPause = async () => {
    if (!audioRef.current || !currentAudioUrl) return;

    if (isPlaying) {
      audioRef.current.pause();
      setIsPlaying(false);
    } else {
      try {
        await audioRef.current.play();
        setIsPlaying(true);

        // Mark as listened on first play - only if current user is the owning agent
        const isOwningAgent = agentUserId && user?.id === agentUserId;
        if (!hasListened && isOwningAgent) {
          await markAsListened();
        }
      } catch (error) {
        console.error('Error playing audio:', error);
        toast.error('Failed to play audio');
      }
    }
  };

  const markAsListened = async () => {
    try {
      const { error } = await supabase
        .from('booking_transcriptions')
        .update({ qa_coaching_audio_listened_at: new Date().toISOString() })
        .eq('booking_id', bookingId);

      if (!error) {
        setHasListened(true);
        onAudioListened?.();
      }
    } catch (error) {
      console.error('Error marking as listened:', error);
    }
  };

  const handleTimeUpdate = () => {
    if (audioRef.current) {
      const currentProgress = (audioRef.current.currentTime / audioRef.current.duration) * 100;
      setProgress(currentProgress);
    }
  };

  const handleLoadedMetadata = () => {
    if (audioRef.current) {
      setDuration(audioRef.current.duration);
    }
  };

  const handleEnded = () => {
    setIsPlaying(false);
    setProgress(0);
  };

  const handleGenerateAudio = async () => {
    setIsGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke('generate-qa-coaching-audio', {
        body: { bookingId }
      });

      if (error) throw error;

      if (data?.audioUrl) {
        setCurrentAudioUrl(data.audioUrl);
        toast.success('QA coaching audio generated by Katty!');
      }
    } catch (error) {
      console.error('Error generating QA coaching audio:', error);
      toast.error('Failed to generate QA coaching audio');
    } finally {
      setIsGenerating(false);
    }
  };

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  // Button variant - matches Jeff's coaching button style
  if (variant === 'button') {
    return (
      <div className="flex items-center gap-2">
        <audio
          ref={audioRef}
          src={currentAudioUrl || ''}
          onTimeUpdate={handleTimeUpdate}
          onLoadedMetadata={handleLoadedMetadata}
          onEnded={handleEnded}
        />
        {currentAudioUrl ? (
          <Button
            onClick={handlePlayPause}
            size="sm"
            variant="outline"
            className={cn("gap-2", isPlaying && "bg-accent/20")}
          >
            {isPlaying ? (
              <>
                <Pause className="h-4 w-4" />
                Pause
              </>
            ) : (
              <>
                <Play className="h-4 w-4" />
                Play Coaching
              </>
            )}
          </Button>
        ) : (
          <Button
            variant="outline"
            size="sm"
            onClick={handleGenerateAudio}
            disabled={isGenerating}
            className="gap-2"
          >
            {isGenerating ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Sparkles className="h-4 w-4" />
            )}
            Generate
          </Button>
        )}
      </div>
    );
  }

  // No audio - show generate card (matching Jeff's style)
  if (!currentAudioUrl) {
    return (
      <div 
        onClick={!isGenerating ? handleGenerateAudio : undefined}
        className={cn(
          "flex items-center gap-3 p-3 rounded-lg border border-accent/30 bg-accent/5 cursor-pointer hover:bg-accent/10 transition-colors",
          isGenerating && "cursor-wait"
        )}
      >
        <div className="w-10 h-10 rounded-full bg-accent/20 flex items-center justify-center">
          {isGenerating ? (
            <Loader2 className="h-5 w-5 text-accent animate-spin" />
          ) : (
            <Sparkles className="h-5 w-5 text-accent" />
          )}
        </div>
        <div className="flex-1">
          <p className="text-sm font-medium">
            {isGenerating ? "Katty is preparing your coaching..." : "Listen to Katty's QA Coaching"}
          </p>
          <p className="text-xs text-muted-foreground">
            {isGenerating ? 'This may take a few seconds' : 'Get personalized feedback on this call'}
          </p>
        </div>
      </div>
    );
  }

  // Audio exists - show player (matching Jeff's card style)
  return (
    <div className="space-y-2">
      <audio
        ref={audioRef}
        src={currentAudioUrl}
        onTimeUpdate={handleTimeUpdate}
        onLoadedMetadata={handleLoadedMetadata}
        onEnded={handleEnded}
      />

      <div className="flex items-center gap-4 p-4 rounded-lg border border-accent/30 bg-gradient-to-r from-accent/10 to-accent/5">
        <button
          onClick={handlePlayPause}
          disabled={isGenerating}
          className="w-12 h-12 rounded-full bg-accent flex items-center justify-center hover:bg-accent/80 transition-colors disabled:opacity-50"
        >
          {isGenerating ? (
            <Loader2 className="h-6 w-6 text-accent-foreground animate-spin" />
          ) : isPlaying ? (
            <Pause className="h-6 w-6 text-accent-foreground" />
          ) : (
            <Play className="h-6 w-6 text-accent-foreground ml-0.5" />
          )}
        </button>
        
        <div className="flex-1">
          <div className="flex items-center justify-between mb-1">
            <span className="text-sm font-medium flex items-center gap-2">
              <Volume2 className="h-4 w-4 text-accent" />
              Katty's QA Coaching
              {qaScore !== undefined && (
                <span className="text-xs text-muted-foreground">
                  ({qaScore}%)
                </span>
              )}
            </span>
            <div className="flex items-center gap-2">
              <span className="text-xs text-muted-foreground">
                {formatTime(duration)}
              </span>
              {hasListened && (
                <Badge variant="outline" className="bg-green-500/10 text-green-600 border-green-500/20 text-xs">
                  <CheckCircle className="h-3 w-3 mr-1" />
                  Listened
                </Badge>
              )}
            </div>
          </div>
          <div className="w-full bg-muted rounded-full h-2">
            <div
              className="bg-accent h-2 rounded-full transition-all duration-200"
              style={{ width: `${progress}%` }}
            />
          </div>
        </div>
      </div>

      {weakestAreas.length > 0 && (
        <div className="px-1">
          <span className="text-xs text-muted-foreground">Focus Areas:</span>
          <div className="flex flex-wrap gap-1 mt-1">
            {weakestAreas.map((area, index) => (
              <Badge key={index} variant="secondary" className="text-xs">
                {area}
              </Badge>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};